baseURL = "https://blog.daipch.cn/"
languageCode = "zh-CN"
title = "ä¸œæœ‰å¯æ˜"
theme = "hyde-hyde"
googleAnalytics = "UA-162149996-2"  # UA-XXXXXXXX-X

## ä¿æŒåˆ†ç±»çš„åŸå§‹åå­—ï¼ˆfalseä¼šåšè½¬å°å†™å¤„ç†ï¼‰
preserveTaxonomyNames = true
## æ˜¯å¦ç¦æ­¢URL Pathè½¬å°å†™
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

[params]
  author = "daipch"
  description = "æŠ€æœ¯ä¸éæŠ€æœ¯çš„æ„Ÿæƒ³å’Œéšç¬”"
  keywords = "daipch,blog,åšå®¢"
  authorimage = "/img/venus.jpg"
  dateformat = "Jan 2, 2006"
  # busuanzi = true #å¯ç”¨ä¸ç®—å­ç½‘é¡µç»Ÿè®¡
  # googleAd = "ca-pub-4031353640611810"  #ca-pub-xxxxxxxxxxxxxx
  # localSearch = true # å¯ç”¨æœ¬åœ°æœç´¢
  mainSections = ["life", "tech"]

  # å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½
  toc = "tocbot"  # æ˜¯å¦å¼€å¯ç›®å½•

  # sidebar, copyright & license
  copyright = "daipch"
  since = 2020
  license = "CC BY-NC-ND 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  showBuiltWith = true

  # ä»£ç é«˜äº®
  highlightjs = true
  highlightjsstyle = "github"

  # navigation
  postNavigation = false

  ## é…ç½® utterancè¯„è®º,æ•™ç¨‹å‚è€ƒ https://utteranc.es/
  UtterancesRepo = "dai-pch/dai-pch.github.io"
  UtterancesIssueTerm = "pathname"
  UtterancesTheme = "github-light"

## Social Accounts
[params.social]
    github = "dai-pch"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "<username>"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    # telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    email = "dpc_work@163.com"
    # gravatar = "your-email@example.com"

## å‹æƒ…é“¾æ¥ï¼Œå¯ä»¥å¤šä¸ª

[[params.links]]
  title = "Jiazhengçš„åšå®¢"
  name = "Jiazhengçš„åšå®¢"
  url = "https://liujiazheng.github.io/"

[[params.links]]
  title = "Changsong Zhangçš„åšå®¢"
  name = "Changsong Zhangçš„åšå®¢"
  url = "https://davidzhangbuaa.github.io/"

## ä¾§è¾¹æ å¹¿å‘Šä½
# [[params.ads]]
#   title = "ã€2019åŒ12ã€‘ALL IN CLoud ä½è‡³1æŠ˜"
#   url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
#   img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

## é…ç½®ç½‘ç«™èœå•

[menu]

  [[menu.main]]
    identifier = "life"
    name = "ğŸ© ç”Ÿæ´»"
    url = "/life/"
    weight = 100

  [[menu.main]]
    identifier = "tech"
    name = "ğŸ–¥ï¸ æŠ€æœ¯"
    url = "/tech/"
    weight = 200

  [[menu.main]]
    identifier = "archives"
    name = "ğŸ“š å½’æ¡£"
    url = "/archives/"
    weight = 300

  [[menu.main]]
    identifier = "about"
    name = "ğŸ¤ª å…³äº"
    url = "/about/"
    weight = 400

